// Echo II: Configuring RTC Alarm for Adafruit Adalogger over Serial
//   Used with adalogger_SLeepRTCAlarm running on SAMD21

import processing.serial.*;
Serial port;

char[] alarmTimes = { // to be generated by a GUI'

  '$', //char(4), '>', // for syncing - could be improved

  char(hour()), char(minute()), char(second()), 
  char(day()), char(month()), char(year()-2000), //'>',

  char(hour()), char(minute()+1), char(0), 
  char(day()), char(month()), char(year()-2000), //'>',

  char(hour()), char(minute()+1), char(10), 
  char(day()), char(month()), char(year()-2000), //'>',

  char(hour()), char(minute()+1), char(20), 
  char(day()), char(month()), char(year()-2000), //'>',

  '\n'}; // is the end character needed?

String alarmTimesStr = new String(alarmTimes);

void setup() {
  println(Serial.list()); // This will be a problem...
  String portName = Serial.list()[1];
  port = new Serial(this, portName, 9600);

  //int numAlarms = 3;
  port.write(alarmTimesStr.getBytes()); //println(alarmTimesStr);
}

int bytesRxd = 0;
void draw() { // nothing is being drawn though!
  while (port.available() > 0) {
    bytesRxd++;
    int inByte = port.read();

    if (bytesRxd == (alarmTimesStr.length() -1)) println();

    if (bytesRxd < (alarmTimesStr.length() -1)) print(inByte);
    else { // need to distinguish times and dates using these numbers
      if (inByte == 47) print("/");
      else if (inByte == 58) print(":");
      else if (inByte == 32) print(" ");
      else print(inByte);
    }
    /*
    if (bytesRxd == 1) print("Data echo'd:\n\t");
     else if (bytesRxd <= (alarmTimesStr.length())) print(inByte);
     
     if (bytesRxd == (alarmTimesStr.length())) print("\nAlarm Set:\n\t");
     
     */
  }
}